# Numerical Python(Numpy) - Part 1

In [1]:
# de facto standard (사실상의 표준)
import numpy as np

In [2]:
a = [1, 2, 3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
list(map(lambda x : 3 * x , a))

[3, 6, 9]

In [4]:
b = np.array([1, 2, 3])
b * 3

array([3, 6, 9])

## 1. Numpy Dimensional Array

In [5]:
a = np.array([1,4,5,8], dtype=float)
a

array([1., 4., 5., 8.])

In [6]:
type(a)

numpy.ndarray

In [9]:
a.dtype, a.shape

(dtype('float64'), (4,))

## 2.Array shape

In [12]:
# Vector(1차원)
vector = np.array([1,4,5,8])
vector, vector.shape

(array([1, 4, 5, 8]), (4,))

In [13]:
# Matix(2차원)
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix.shape)
print(matrix)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [15]:
# Tensor(3차원 이상)
tensor = np.arange(1, 25).reshape(2,3,4)  
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [16]:
tensor.shape

(2, 3, 4)

In [17]:
vector.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [18]:
# element의 갯수
vector.size, matrix.size, tensor.size   

(4, 6, 24)

In [20]:
# data type
# float32 : 32bit로 표시 - single precision
# float64 : 64bit로 표시 - double precision
a = np.array([1,2,3], dtype=np.float32)   # float로만 하면 float64가 된다
a

array([1., 2., 3.], dtype=float32)

In [22]:
b = np.array([1,2,3], dtype=np.int16)   # default는 int32이다
b 

array([1, 2, 3], dtype=int16)

### reshape  : 인수값은 tuple이기 때문에 일차원으로 하려면 (-1, )로 해야지 (-1)은 안된다

In [23]:
matrix.shape


(2, 3)

In [24]:
matrix.reshape(6,)   # 일차원으로 펼치고 싶다면 (6,)

array([1, 2, 3, 4, 5, 6])

In [25]:
matrix.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
# -1은 numpy가 알아서 맞춰줌 (단, size가 동일)
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [30]:
matrix.reshape(1, -1)   # 행이 1, 열이 6

array([[1, 2, 3, 4, 5, 6]])

In [32]:
matrix.reshape(-1, 1)   # 행이 6, 열이 1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [27]:
matrix.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
matrix.reshape(3, -1).shape

(3, 2)

In [29]:
tensor.reshape(4, -1).shape

(4, 6)

In [46]:
### flatten : 일차원으로 변경시켜준다
tensor.flatten(), tensor.reshape(-1, ), all(tensor.flatten() == tensor.reshape(-1, ))

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 True)

In [39]:
# y = w * x + b
np.array([[1,2,3]]).shape, np.array([[1],[2],[3]]).shape

((1, 3), (3, 1))

## 3. Indexing & Slicing

Indexing

In [40]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
matrix[0][1]

2

In [42]:
matrix[0, 1]

2

In [47]:
tensor[1,1,2]

19

### slincing

In [49]:
b = np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
# 5,6,9,10
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [51]:
# 5, 6, 7, 9, 10, 11
b[1:3, 1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [57]:
# 1,3,9,11
b[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [59]:
b[[0,2],[1,3]]

array([ 1, 11])

In [62]:
# 대문자는 2차원이상의 데이터, 소문자는 1차원의 데이터
X, y = b[:, :-1], b[:, -1]
X.shape, y.shape, X, y

((4, 3), (4,), array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14]]), array([ 3,  7, 11, 15]))