In [2]:
import numpy as np

## 1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오
- 10 20 30 40
- 50 60 70 80

In [5]:
a = np.arange(10, 90, 10, np.int16).reshape(2, -1)
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]], dtype=int16)

## 2. 다음 행렬과 같은 행렬이 있다

In [6]:
m = np.arange(15).reshape(3,-1)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
# 1.이 행렬에서 값 7 을 인덱싱한다
m[1, 2]

7

In [8]:
# 2.이 행렬에서 값 14 을 인덱싱한다
m[-1, -1]

14

In [9]:
# 3. 이 행렬에서 배열 [6, 7] 을 슬라이싱한다
m[1, [1,2]]

array([6, 7])

In [10]:
# 4. 이 행렬에서 배열 [7, 12] 을 슬라이싱한다
m[[1,2], 2]

array([ 7, 12])

In [12]:
# 5. 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다
m[:2, 3:]

array([[3, 4],
       [8, 9]])

## 3. 2번의 행렬 m 을 1 차원 벡터 f 로 변환한 후 다음의 문제를 푸시오

In [13]:
f = m.flatten()
f

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
# 1. 이 배열에서 3 의 배수를 찾아라
f[f % 3 == 0]

array([ 0,  3,  6,  9, 12])

In [16]:
# 2. 이 배열에서 4 로 나누면 1 이 남는 수를 찾아라
f[f % 4 == 1]

array([ 1,  5,  9, 13])

In [22]:
# 3. 이 배열에서 3 으로 나누면 나누어지고 4 로 나누면 1 이 남는 수를 찾아라
f[np.logical_and((f % 3 == 0), (f % 4 == 1))]

array([9])

## 4. 값을 직접 입력하지 말고 우측의 행렬을 만드시오

In [35]:
a = np.identity(5, dtype=np.int16) * 2 + np.eye(5, k=1) + np.eye(5, k=-1) * 3
print(a)

[[2. 1. 0. 0. 0.]
 [3. 2. 1. 0. 0.]
 [0. 3. 2. 1. 0.]
 [0. 0. 3. 2. 1.]
 [0. 0. 0. 3. 2.]]


## 5. 0 에서 10 까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구하시오

In [39]:
np.random.seed(123)
a = np.random.uniform(low=0, high=10.0, size=30).reshape(5, -1)
a.shape

(5, 6)

In [40]:
# 1.전체의 최대값
np.max(a)

9.807641983846155

In [41]:
# 2.각행의 합
np.sum(a, axis=1)

array([29.03350173, 36.1087108 , 19.92233289, 38.82690549, 25.60144353])

In [42]:
# 3.각행의 최대값
np.max(a, axis=1)

array([7.1946897 , 9.80764198, 7.37995406, 8.49431794, 7.22443383])

In [43]:
# 4.각열의 평균
np.mean(a, axis=0)

array([6.73960077, 3.77086694, 4.20403445, 5.51824544, 4.52661618,
       5.13921512])

In [44]:
# 5.각열의 최소값
np.min(a, axis=0)

array([4.38572245, 0.59677897, 2.26851454, 2.28263231, 1.8249173 ,
       1.75451756])

## 6. 다음 배열은 첫번째 행 ( 에 학번 , 두번째 행에 영어 성적 , 세번째 행에 수학 성적을 적은 배열이다 . 영어 성적을 기준으로 각 열을 재정렬하시오

In [45]:
a = np.array([[1, 2, 3, 4], [46, 99, 100, 71], [81, 59, 90, 100]])
a

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [56]:
eng_idx = np.argsort(a[1])
eng_idx

array([0, 3, 1, 2])

In [58]:
eng_sort = a.T[eng_sort].T
eng_sort

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [59]:
eng_idx_reverse = np.argsort(a[1])[::-1]
eng_idx_reverse

array([2, 1, 3, 0])

In [61]:
eng_sort_reverse = a.T[eng_idx_reverse].T
eng_sort_reverse

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

## 7. 주사위를 100 번 던지는 가상 실험을 파이썬으로 작성하고, 던져서 나오는 숫자의 평균을 구하시오

In [127]:
np.random.seed(123)
dice_100 = np.random.multinomial(n=100, pvals=[1/6]*6, size=1)
print(dice_100)

dice_nums = np.arange(1,7).reshape(-1, 1)
print(dice_nums)

print(dice_100.shape, dice_nums.shape)

dice_sum = np.dot(dice_100, dice_nums)[0][0]
print(dice_sum)

dice_mean = dice_sum / np.sum(dice_100)
diec_mean = dice_mean
print(dice_mean)

[[18 14 14 18 20 16]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(1, 6) (6, 1)
356
3.56


In [125]:
dice_sum[0][0]

356

In [81]:
np.random.seed(123)
dice_100 = np.random.multinomial(n=100, pvals=[1/6]*6, size=1)
print(dice_100)

dice_nums = np.arange(1, 7)
print(dice_nums)

dice_sums = dice_100.reshape(-1, ) * dice_nums
print(dice_sums)

dice_mean = np.sum(dice_sums) / 100
print(dice_mean)

[[18 14 14 18 20 16]]
[1 2 3 4 5 6]
[ 18  28  42  72 100  96]
3.56


## 가격이 10,000 원인 주식이 있다 . 이 주식의 일간 수익률 은 기댓값이 0% 이고 표준편차가 1% 인 표준 정규 분포를 따른다고 하자 . 250 일 동안의 주가를 무작위로 생성하시오

In [118]:
np.random.seed(123)
prices = []
prices.append(10000)
price = 10000

for i in range(99):
    
    pct_change = np.random.normal(0.0, 0.01)
    price = np.round(price * (1 + pct_change), 2)
    prices.append(price)

print(prices)
    

[10000, 9891.44, 9990.09, 10018.36, 9867.45, 9810.36, 9972.37, 9730.37, 9688.64, 9811.29, 9726.25, 9660.22, 9651.07, 9795.01, 9732.43, 9689.22, 9647.13, 9859.94, 10075.56, 10176.72, 10216.02, 10291.35, 10444.77, 10347.02, 10468.68, 10337.42, 10271.49, 10364.66, 10216.58, 10202.27, 10114.35, 10088.5, 9806.16, 9632.44, 9565.02, 9653.73, 9636.97, 9637.24, 9703.57, 9618.22, 9645.5, 9567.82, 9402.52, 9365.77, 9419.51, 9451.4, 9450.28, 9676.37, 9716.32, 9811.42, 10031.01, 9901.2, 9798.35, 9969.21, 9889.65, 9892.59, 9998.37, 10087.43, 10264.45, 10417.97, 10529.38, 10448.02, 10531.07, 10564.17, 10424.06, 10571.8, 10657.14, 10661.99, 10637.14, 10509.68, 10530.65, 10579.98, 10492.04, 10613.98, 10497.52, 10274.65, 10381.48, 10339.6, 10326.57, 10240.08, 10075.63, 10202.1, 10131.82, 10300.1, 10383.25, 10350.57, 10238.17, 10163.18, 10039.95, 10249.5, 10266.35, 10384.43, 10252.82, 10271.38, 10392.36, 10357.54, 10464.34, 10350.85, 10209.72, 10248.46]


In [119]:
np.random.seed(123)
prices = []
prices.append(10000)
price = 10000

for i in range(99):
    
    pct_change = np.random.normal(0.0, 0.01)
    price = np.round(price * (1 + pct_change), 2)
    print(price, end=' ')
    prices.append(price)


    

9891.44 9990.09 10018.36 9867.45 9810.36 9972.37 9730.37 9688.64 9811.29 9726.25 9660.22 9651.07 9795.01 9732.43 9689.22 9647.13 9859.94 10075.56 10176.72 10216.02 10291.35 10444.77 10347.02 10468.68 10337.42 10271.49 10364.66 10216.58 10202.27 10114.35 10088.5 9806.16 9632.44 9565.02 9653.73 9636.97 9637.24 9703.57 9618.22 9645.5 9567.82 9402.52 9365.77 9419.51 9451.4 9450.28 9676.37 9716.32 9811.42 10031.01 9901.2 9798.35 9969.21 9889.65 9892.59 9998.37 10087.43 10264.45 10417.97 10529.38 10448.02 10531.07 10564.17 10424.06 10571.8 10657.14 10661.99 10637.14 10509.68 10530.65 10579.98 10492.04 10613.98 10497.52 10274.65 10381.48 10339.6 10326.57 10240.08 10075.63 10202.1 10131.82 10300.1 10383.25 10350.57 10238.17 10163.18 10039.95 10249.5 10266.35 10384.43 10252.82 10271.38 10392.36 10357.54 10464.34 10350.85 10209.72 10248.46 

In [114]:
np.round(np.random.normal(loc=0, scale=0.01, size=10), 3)

array([-0.016, -0.004,  0.012, -0.007,  0.005,  0.01 ,  0.003, -0.014,
       -0.003,  0.02 ])